### PR TITLE
Add tunnel url to registry. r=fabrice

### PR DESCRIPTION
**Pull request by ferjm**

### CODE REVIEW

**Comment by ferjm** [comment]
Given that the storage content is really not valuable for us, we can safely remove the existing sqlite file from the dev server before applying these changes.

r? @fabricedesre

**Comment by michielbdejong** [comment]
@ferjm can we also add the public-local URL? So the Box would post something like the JSON I described in https://github.com/fxbox/foxbox/pull/77#issuecomment-196216450

**Comment by michielbdejong** [comment]
In fact, I'm thinking, why impose a schema at all? We could just make this service a lot "dumber", just a message bus where anybody can broadcast a message, and anybody can see which messages were sent from the same outgoing IP address.

That makes it a lot clearer what the assumptions are, and it decouples the code of this server from the function we use it for.

**Comment by michielbdejong** [comment]
I'm still thinking, why impose a schema at all? We could just change `local_ip` to `msg`, that way the Box can decide which message string it wants to announce via this service.

**Comment by ferjm** [comment]
Yes, we could do that.

@fabricedesre any objection?

**Comment by fabricedesre** [comment]
We can't let clients send arbitrary large message and basically use the registration server as a poor man's db. So I'm fine with having a more relaxed schema, but we can't be fully open ended I fear.

**Pull request merged**
